name: Build

on: [push]

jobs:
  build:
    strategy:
      matrix:
        board: [d1_mini, esp32doit-devkit-v1]
        source: [SimpleRestServer, AsyncRestServer]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
            .pio/build
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install PlatformIO Core
        run: |
          pip install -U platformio
          platformio update
          pio pkg install -l 'ArduinoJson@~6.20'
          pio pkg install -l 'PathVariableHandlers@~2.0'
          pio pkg install -l 'me-no-dev/ESP Async WebServer'

      - name: Build PlatformIO
        run: |
          pio ci \
            --board=${{ matrix.board }} \
            --lib=. \
            --project-option="build_flags=${{ matrix.source == "AsyncRestServer" && "-DRICH_HTTP_ASYNC_WEBSERVER" || "" }}" \
          examples/${{ matrix.source }}